// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSKLjZnEpnaDXNWqdNoZoVznDRpXeWgiE',
    appId: '1:391747560334:web:3360fd53c79af7ed6a7adf',
    messagingSenderId: '391747560334',
    projectId: 'alertarural-26ff2',
    authDomain: 'alertarural-26ff2.firebaseapp.com',
    databaseURL: 'https://alertarural-26ff2-default-rtdb.firebaseio.com',
    storageBucket: 'alertarural-26ff2.appspot.com',
    measurementId: 'G-LDC72PTJNR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6vO0j2doFaobtcOIj7NDHEqGeBG7c-q0',
    appId: '1:391747560334:android:8bfa350aafd7c9de6a7adf',
    messagingSenderId: '391747560334',
    projectId: 'alertarural-26ff2',
    databaseURL: 'https://alertarural-26ff2-default-rtdb.firebaseio.com',
    storageBucket: 'alertarural-26ff2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApjqdnQJI7ocz-kZaaXsqN03UqzoSk6gw',
    appId: '1:391747560334:ios:8a8140b39b14a6356a7adf',
    messagingSenderId: '391747560334',
    projectId: 'alertarural-26ff2',
    databaseURL: 'https://alertarural-26ff2-default-rtdb.firebaseio.com',
    storageBucket: 'alertarural-26ff2.appspot.com',
    iosBundleId: 'com.example.alertarural',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApjqdnQJI7ocz-kZaaXsqN03UqzoSk6gw',
    appId: '1:391747560334:ios:8a8140b39b14a6356a7adf',
    messagingSenderId: '391747560334',
    projectId: 'alertarural-26ff2',
    databaseURL: 'https://alertarural-26ff2-default-rtdb.firebaseio.com',
    storageBucket: 'alertarural-26ff2.appspot.com',
    iosBundleId: 'com.example.alertarural',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSKLjZnEpnaDXNWqdNoZoVznDRpXeWgiE',
    appId: '1:391747560334:web:02cbd991e2693f556a7adf',
    messagingSenderId: '391747560334',
    projectId: 'alertarural-26ff2',
    authDomain: 'alertarural-26ff2.firebaseapp.com',
    databaseURL: 'https://alertarural-26ff2-default-rtdb.firebaseio.com',
    storageBucket: 'alertarural-26ff2.appspot.com',
    measurementId: 'G-BB0FGQMMKW',
  );

}